#!/usr/bin/env python3
"""Scalar-[alpha/Fe] mock recovery: generate a self-mock on the real
alpha grid and fit it with NUTS (Phase B of AFE_MOCK_TEST_DESIGN.md).

Minimal first-light configuration, deliberately matching the validated
afe_val_05 setup: continuum-only (no dust, no nebular — CSPBasis_afe has
no nebular by construction), free parameters {sfh (per-bin), Z, afe,
logmass}, fixed zred, single Spectrum observation at R=1000.  Once this
recovers cleanly, widen toward the campaign config (dust on, sigma_smooth,
noise jitter, her SFH parametrization) following the design doc.

Self-mock: the mock is generated by the SAME forward model that fits it,
so this tests inference (bias, coverage, the Z-afe ridge), not template
mismatch.

Usage:
    python run_afe_mock_recovery.py \
        --grid ssp_data_afe_c3k.h5 --out runs/afe_mocks/t00 \
        --afe-true 0.3 --z-true -1.9 --snr 25 --sfh fastquench --seed 42

FSPS is not needed; JAX GPU is strongly recommended for the fit.
"""
import argparse
import json
from pathlib import Path

import numpy as np


SFH_LIBRARY = {
    # per-bin SFR (Msun/yr) on the 7 bins of an 8-node lookback grid,
    # index 0 = youngest bin (today), oldest last.
    "fastquench": np.array([1e-3, 1e-3, 2e-3, 1e-2, 0.2, 2.0, 6.0]),
    "extended":   np.array([0.3, 0.5, 0.8, 1.0, 1.2, 1.5, 1.5]),
    "residual":   np.array([0.15, 5e-2, 1e-2, 0.1, 1.0, 3.0, 4.0]),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--afe-true", type=float, default=0.3)
    ap.add_argument("--z-true", type=float, default=-1.9,
                    help="log10 absolute total Z (ssp_lgmet units)")
    ap.add_argument("--logmass-true", type=float, default=10.0)
    ap.add_argument("--zred", type=float, default=1.0)
    ap.add_argument("--snr", type=float, default=25.0)
    ap.add_argument("--sfh", choices=sorted(SFH_LIBRARY), default="fastquench")
    ap.add_argument("--resolution", type=float, default=1000.0,
                    help="spectral R (smoothtype='R')")
    ap.add_argument("--wave-obs", type=float, nargs=2,
                    default=(6000.0, 18000.0),
                    help="observed-frame wavelength range [A]")
    ap.add_argument("--n-pix", type=int, default=1200)
    ap.add_argument("--num-samples", type=int, default=2000)
    ap.add_argument("--num-chains", type=int, default=4)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    import jax
    import jax.numpy as jnp
    from ceridwen.ssps.ssp_data_afe import SSPDataAfe
    from ceridwen.csp.csp_afe import CSPBasis_afe
    from ceridwen.model.model import SedModel
    from ceridwen.observation.observation import Spectrum
    from ceridwen.sampler.priors import Uniform, Normal, LogNormal
    from ceridwen.cosmology import age_gyr
    from ceridwen.fit import fitSED

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    # ---------------------------------------------------------- forward model
    ssp = SSPDataAfe.load(args.grid)
    if ssp.n_afe == 1:
        print("WARNING: n_afe=1 grid (null build) — afe will be inert; "
              "this run is only useful as the library-null control.")

    t_univ = float(age_gyr(args.zred)) - 0.05          # Gyr at zred
    lookback = jnp.linspace(0.0, t_univ, 8)            # 8 nodes -> 7 bins
    sfh_true = SFH_LIBRARY[args.sfh]

    csp = CSPBasis_afe(
        ssp,
        theta={"lookback_time": lookback,
               "sfh": jnp.asarray(sfh_true),
               "Z": jnp.array([args.z_true]),
               "afe": jnp.array([args.afe_true])},
        zh_const=True,
        add_dust=False, add_diffuse_dust=False, add_dust_emission=False,
        add_igm=False,
        sigma_losvd_kms=200.0,
        verbose=True,
    )

    theta_true = dict(csp.theta_init)
    theta_true["logmass"] = jnp.array([args.logmass_true])
    theta_true["zred"] = jnp.array([args.zred])

    # ---------------------------------------------------------- mock spectrum
    wave_obs = np.linspace(*args.wave_obs, args.n_pix)
    # Template observation used only to project the truth onto the pixel grid.
    proj = Spectrum(wavelength=wave_obs,
                    flux=np.zeros_like(wave_obs),
                    uncertainty=np.ones_like(wave_obs),
                    resolution=args.resolution, smoothtype="R",
                    name="mockspec")
    proj.setup_for_model(csp.wave, zred=args.zred)
    truth_flux = np.asarray(csp.predict(theta_true, [proj])["mockspec"])

    sigma = np.abs(truth_flux) / args.snr
    mock_flux = truth_flux + rng.normal(0.0, sigma)

    obs = Spectrum(wavelength=wave_obs, flux=mock_flux, uncertainty=sigma,
                   resolution=args.resolution, smoothtype="R",
                   name="mockspec")

    # ----------------------------------------------------------------- truths
    truths = {
        "afe": args.afe_true, "Z": args.z_true,
        "logmass": args.logmass_true, "zred": args.zred,
        "snr": args.snr, "sfh_class": args.sfh,
        "sfh": sfh_true.tolist(),
        "lookback_gyr": np.asarray(lookback).tolist(),
        "grid": str(args.grid), "n_afe": int(ssp.n_afe),
        "seed": args.seed,
    }
    (out / "truths.json").write_text(json.dumps(truths, indent=2))

    # ------------------------------------------------------------------- fit
    afe_lo = float(np.asarray(ssp.ssp_afe).min())
    afe_hi = float(np.asarray(ssp.ssp_afe).max())
    z_lo = float(np.asarray(ssp.ssp_lgmet).min())
    z_hi = float(np.asarray(ssp.ssp_lgmet).max())

    priors = {
        "Z":       Uniform(low=z_lo, high=z_hi),
        "logmass": Normal(mean=args.logmass_true, sigma=1.0),
        # per-bin SFR: weakly-informative LogNormal around the truth scale;
        # replace with the campaign SFH parametrization (logsfr_ratios
        # transform) once first-light recovery passes.
        "sfh":     LogNormal(mean=float(np.log(np.median(sfh_true))),
                             sigma=2.0),
    }
    if ssp.n_afe > 1:
        priors["afe"] = Uniform(low=afe_lo, high=afe_hi)

    theta_init = dict(csp.theta_init)
    theta_init["logmass"] = jnp.array([args.logmass_true])
    if ssp.n_afe == 1:
        theta_init.pop("afe", None)

    model = SedModel(
        csp,
        observations=[obs],
        priors=priors,
        zred=args.zred,
    )
    # Seed the sampler at the truth-adjacent init already in theta_init.
    model.theta_init.update(theta_init)

    result = fitSED(
        model, [obs],
        output_dir=out,
        sampler="nuts",
        rng_key=jax.random.PRNGKey(args.seed),
        sampler_kwargs={"num_samples": args.num_samples,
                        "num_chains": args.num_chains},
    )

    # ------------------------------------------------------------- summary
    print("\n=== recovery summary (median [16, 84]) ===")
    for name, true_val in (("afe", args.afe_true), ("Z", args.z_true),
                           ("logmass", args.logmass_true)):
        if name not in result.samples:
            continue
        s = np.asarray(result.samples[name]).reshape(-1)
        q16, q50, q84 = np.percentile(s, [16, 50, 84])
        pull = (q50 - true_val) / (0.5 * (q84 - q16) + 1e-30)
        print(f"  {name:8s}: {q50:+.3f} [{q16:+.3f}, {q84:+.3f}]   "
              f"truth {true_val:+.3f}   pull {pull:+.2f}")
    print(f"\nresult: {out}/ceridwen_result.h5")


if __name__ == "__main__":
    main()
